//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by edres.rc
//
#define IDC_CURSOR1                     1
#define IDC_ZOOM                        1
#define IDC_CURSOR2                     2
#define IDC_ABSREL                      2
#define IDC_CURSOR3                     3
#define IDC_SMALLCREATE                 3
#define IDCANCEL2                       3
#define IDC_CURSOR4                     4
#define IDC_POINTER                     4
#define IDC_CURSOR5                     5
#define IDC_BIGCREATE                   5
#define IDC_CURSOR6                     6
#define IDC_ANGLE                       6
#define IDC_CURSOR7                     7
#define IDC_MOVE                        7
#define IDR_MENU                        108
#define IDR_ACCELERATORS                111
#define IDD_ABOUT                       112
#define IDR_MENU1                       113
#define ID_TOOLS_BLOB                   114
#define ID_TOFRONT115                   115
#define ID_TOBACK116                    116
#define ID_TOOLS_ANGLES                 117
#define ID_Menu                         118
#define ID_TOOLS_JUMP                   119
#define ID_EDIT_UNDO120                 120
#define ID_EDIT_REDO121                 121
#define ID_EDIT_MARK                    122
#define ID_TOOLS_USERCOLOURS            123
#define ID_TOOLS_USERTHICKNESS          124
#define IDD_USER                        125
#define ID_TOOLS_SNAP                   126
#define ID_TOOLS_GRID                   127
#define IDR_DATA1                       129
#define IDD_INSTALL                     130
#define IDD_EXPORT                      131
#define ID_EDIT_FLIP                    132
#define ID_TOOLS_ZOOM                   133
#define ID_ZOOM_ZOOMIN                  134
#define ID_ZOOM_ZOOMOUT                 135
#define ID_ZOOM_ZOOMFULL                136
#define ID_TOOLS_TEST                   137
#define ID_TOOLS_BACKDROP               139
#define ID_TOOLS_BITMAPS                140
#define IDD_BITMAPS                     141
#define IDD_DIALOG1                     142
#define IDD_RENAME                      142
#define IDD_UPRIGHT                     143
#define ID_TOOLS_CHECKUPRIGHT           144
#define IDD_DIALOG2                     145
#define IDD_STYLES                      145
#define ID_TOOLS_STYLES                 146
#define IDI_ICON1                       148
#define ID_TOOLS_SHOWJOINTS             155
#define ID_TOOLS_SHOWINVISIBLES         156
#define ID_TOOLS_SHOW                   157
#define ID_TOOLS_CATEGORY               158
#define IDD_ASSOCIATE                   159
#define IDD_RULE                        160
#define ID_FILE_EXPORTAVI               161
#define ID_EXPORTCANCEL                 162
#define IDD_EFFECTS                     164
#define ID_TOOLS_EFFECTS                165
#define ID_TOOLS_USERCUMULATIVES        166
#define ID_TOOLS_TARGETFRAMERATE        167
#define ID_VERSION                      1000
#define ID_HREF                         1001
#define IDC_EDIT                        1002
#define IDC_TITLE                       1003
#define IDC_EXISTS1                     1006
#define IDC_EXISTS2                     1007
#define IDC_DOESNTEXIST                 1008
#define IDC_PREVIEW                     1009
#define IDC_STICK_CURRENT               1010
#define IDC_RADIO2                      1011
#define IDC_TIMEFIXED                   1011
#define IDC_MUSIC_STARWARS              1013
#define IDC_MUSIC_KYLIE                 1014
#define IDC_MUSIC_MOBY                  1015
#define IDC_WIDTH                       1016
#define IDC_HEIGHT                      1017
#define IDC_PERIOD                      1018
#define IDC_TIME                        1018
#define IDC_LENGTH                      1019
#define IDC_FPS                         1019
#define IDC_STICK_PROCESSION            1021
#define IDC_LIST                        1022
#define IDC_PICTURE                     1023
#define IDC_ADD                         1024
#define IDC_DELETE                      1025
#define IDC_RENAME                      1026
#define IDC_FIX                         1027
#define IDC_ALWAYSCHECK                 1028
#define IDC_UPRIGHTREPORT               1029
#define IDC_BUTTON1                     1033
#define IDC_CHANGE                      1033
#define IDC_UP                          1033
#define IDC_WAVBROWSE                   1033
#define IDC_INSTALLPROMPT               1037
#define IDC_RULES                       1038
#define IDC_RECENTS                     1039
#define IDC_MODIFY                      1040
#define IDC_REMOVE                      1042
#define IDC_DOWN                        1043
#define IDC_HELPBTN                     1044
#define IDC_ARTIST                      1046
#define IDC_FILENAME                    1047
#define IDC_STICK                       1048
#define IDC_EDIT5                       1049
#define IDC_REGEXP                      1049
#define IDC_SILENTDANCING               1049
#define IDC_STICK2                      1050
#define IDC_STICKRE                     1050
#define IDC_SILENTTHRASHING             1050
#define IDC_DANCETOWAV                  1051
#define IDC_WAVNAME                     1052
#define IDC_TIMEWAV                     1053
#define IDC_SHOWCOMPRESSION             1054
#define IDC_PROCESSIONLIST              1055
#define IDC_EDIT1                       1056
#define IDC_PROCTIME                    1056
#define IDC_EFFECT                      1057
#define IDC_LIST1                       1059
#define IDC_LIST2                       1060
#define IDC_EDIT2                       1062
#define ID_FILE_SAVEAS                  40003
#define ID_FILE_EXIT                    40005
#define ID_EDIT_DELETE                  40009
#define ID_TOOLS_HITTEST                40011
#define ID_TOOLS_SHOWANGLES             40013
#define ID_TOOLS_ZOOMMODE               40015
#define ID_TOOLS_EDITMODE               40016
#define ID_TOOLS_CREATEMODE             40017
#define ID_EDIT_INSERT                  40018
#define ID_EDIT_ENLARGE                 40019
#define ID_EDIT_SHRINK                  40020
#define ID_HELP_ABOUT                   40023
#define ID_HELP_HELP                    40024
#define ID_FIXED                        40025
#define ID_LEFT                         40026
#define ID_RIGHT                        40027
#define ID_DIFFERENCE                   40028
#define ID_1                            40029
#define ID_2                            40030
#define ID_3                            40031
#define ID_4                            40032
#define ID_5                            40033
#define ID_6                            40034
#define ID_VISIBILITY                   40039
#define ID_LINETYPE                     40040
#define ID_RED                          40041
#define ID_GREEN                        40042
#define ID_BLUE                         40043
#define ID_YELLOW                       40044
#define ID_BLACK                        40045
#define ID_PURPLE                       40046
#define ID_WHITE                        40047
#define ID_HEAVY                        40048
#define ID_MEDIUM                       40049
#define ID_THIN                         40050
#define ID_INVERT                       40051
#define ID_0                            40052
#define ID_TOFRONT                      40054
#define ID_TOBACK                       40055
#define ID_NEGATIVE                     40056
#define ID_CLEFT                        40064
#define ID_CRIGHT                       40065
#define ID_CUP                          40066
#define ID_CDOWN                        40067
#define ID_ZOOMIN                       40076
#define ID_ZOOMOUT                      40077
#define ID_ZOOMFULL                     40078
#define ID_STYLEA                       40093
#define ID_STYLEB                       40094
#define ID_STYLED                       40096
#define ID_STYLEE                       40097
#define ID_STYLEF                       40098
#define ID_STYLEG                       40099
#define ID_STYLEH                       40100
#define ID_STYLEI                       40101
#define ID_STYLEJ                       40102
#define ID_STYLEK                       40103
#define ID_STYLEL                       40104
#define ID_STYLEM                       40105
#define ID_STYLEN                       40106
#define ID_STYLEO                       40107
#define ID_STYLEP                       40108
#define ID_STYLEQ                       40109
#define ID_STYLER                       40110
#define ID_STYLES                       40111
#define ID_STYLET                       40112
#define ID_STYLEZZZZ                    40114
#define ID_FILE_NEW                     57600
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_NEW_FRAME               0xE10D
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         40116
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
